### ISSUE TITLE
May Update

### ISSUE THREAD

**Issue by Lt-Sparky** [Shad0wlife/DSP_AssemblerUI#1]
Love this mod but it quit working with the May Update

**Comment by Shad0wlife** [comment]
Thank you for reporting. I'll look into it as soon as I have access to my dev PC.

**Comment by kurakart** [comment]
Any news? This was one of those mods you can't live without.

**Comment by Lt-Sparky** [comment]
Havent heard a thing and no this isnt one of thoes mods its just a very usefull quality of life mod....

**Comment by Shad0wlife** [comment]
Ah crap, I'm very sorry. I asked around on the DSP discord if tyr0wl was there, because I wanna use stuff he did in his fork, but it seems like he wasn't and then I forgot again. *facepalm*

I'll go try and fix it first and then see about tyr0wl's cleanup changes afterwards. Maybe I can reach them via github.

**Comment by kurakart** [comment]
No worries dude :) You're just doing this voluntarily, I understand.

**Comment by Shad0wlife** [comment]
News: almost done, just fixing up some stuff from the fork for miners.

Also, known issue (which I'm not gonna fix in this update but later) that a breaking error can occur when playing MP with nebula.

**Comment by Shad0wlife** [comment]
**Update is up!**
The potential issue with nebula still exists and will be my next todo. Might open an issue if I get around to actually testing specifics about it again.

**Comment by kurakart** [comment]
thanks guy, you're the best!
